### ISSUE TITLE
empty huggingface model

### ISSUE THREAD

**Issue by Chaoqi-LIU** [bytedance/IRASim#4]
https://huggingface.co/IRASim

this is empty as of 20:21 Oct 23, 2024, CT.

**Comment by Chaoqi-LIU** [comment]
```
Traceback (most recent call last):
  File "/home/chaoqi/anaconda3/envs/irasim/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 371, in load_config
    config_file = hf_hub_download(
  File "/home/chaoqi/anaconda3/envs/irasim/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/chaoqi/anaconda3/envs/irasim/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'IRASim/pretrained_models/stabilityai/stable-diffusion-xl-base-1.0'. Use `repo_type` argument if needed.
```

this was the error msg

**Comment by zhufangqi00** [comment]
Hi, you should use a relative path or 'stabilityai/stable-diffusion-xl-base-1.0'. The datasets are not located at https://huggingface.co/IRASim; I only uploaded the paper there.
